# Generated by Django 5.1.6 on 2025-08-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="receipt_url",
            new_name="card_payment_link",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="clickpesa_reference",
            new_name="clickpesa_payment_reference",
        ),
        migrations.RenameField(
            model_name="paymentmethod",
            old_name="mobile_money_provider",
            new_name="mobile_provider",
        ),
        migrations.RenameField(
            model_name="payoutrequest",
            old_name="mobile_money_provider",
            new_name="mobile_provider",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="clickpesa_status",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="mobile_money_receipt",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="clickpesa_payment_method_id",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="mobile_money_number",
        ),
        migrations.RemoveField(
            model_name="payoutrequest",
            name="clickpesa_payout_id",
        ),
        migrations.RemoveField(
            model_name="payoutrequest",
            name="mobile_money_number",
        ),
        migrations.AddField(
            model_name="payment",
            name="clickpesa_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="clickpesa_order_reference",
            field=models.CharField(default="", max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="collected_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="mobile_provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("mobile_money", "Mobile Money"),
                    ("cash", "Cash on Delivery"),
                ],
                default="mobile_money",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="payoutrequest",
            name="bank_account_last4",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="payoutrequest",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="payment",
            name="clickpesa_transaction_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("settled", "Settled"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="clickpesa_refund_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="refund",
            name="reason",
            field=models.CharField(
                choices=[
                    ("duplicate", "Duplicate"),
                    ("fraudulent", "Fraudulent"),
                    ("requested_by_customer", "Requested by Customer"),
                    ("order_canceled", "Order Canceled"),
                    ("vendor_rejected", "Vendor Rejected Order"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
