# Generated by Django 5.1.6 on 2025-08-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_rename_receipt_url_payment_card_payment_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="card_payment_link",
            new_name="clickpesa_payment_link",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="phone_number",
            new_name="mobile_number",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="clickpesa_message",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="clickpesa_transaction_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="collected_amount",
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="clickpesa_order_reference",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="clickpesa_payment_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="mobile_provider",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("mobile_money", "Mobile Money"),
                    ("cash", "Cash on Delivery"),
                ],
                default="card",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially Refunded"),
                    ("pending_admin_approval", "Pending Admin Approval"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
