# Generated by Django 5.1.6 on 2025-08-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payoutrequest_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cart_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
