# Generated by Django 5.1.6 on 2025-08-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0003_rename_card_payment_link_payment_clickpesa_payment_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="clickpesa_payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
