# Generated by Django 5.1.6 on 2025-08-13 21:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("route_name", models.CharField(max_length=100)),
                (
                    "total_distance",
                    models.FloatField(help_text="Total distance in kilometers"),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="Estimated duration in minutes"),
                ),
                (
                    "actual_duration",
                    models.IntegerField(
                        blank=True, help_text="Actual duration in minutes", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "optimization_score",
                    models.FloatField(
                        blank=True, help_text="Route efficiency score", null=True
                    ),
                ),
                (
                    "fuel_estimate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dispatcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("en_route_pickup", "En Route to Pickup"),
                            ("arrived_pickup", "Arrived at Pickup"),
                            ("picked_up", "Picked Up"),
                            ("en_route_delivery", "En Route to Delivery"),
                            ("arrived_delivery", "Arrived at Delivery"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                (
                    "distance_traveled",
                    models.FloatField(
                        blank=True, help_text="Distance in kilometers", null=True
                    ),
                ),
                (
                    "time_to_pickup",
                    models.IntegerField(
                        blank=True, help_text="Time in minutes", null=True
                    ),
                ),
                (
                    "time_to_delivery",
                    models.IntegerField(
                        blank=True, help_text="Time in minutes", null=True
                    ),
                ),
                ("driver_notes", models.TextField(blank=True)),
                (
                    "customer_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("customer_feedback", models.TextField(blank=True)),
                ("en_route_pickup_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_pickup_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("en_route_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dispatcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_dispatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch",
                        to="orders.order",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatches",
                        to="dispatch.dispatchroute",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "location_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "location_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="dispatch.dispatch",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dispatch status histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="dispatchroute",
            index=models.Index(
                fields=["driver"], name="dispatch_di_driver__6eeccc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchroute",
            index=models.Index(fields=["status"], name="dispatch_di_status_91e3b0_idx"),
        ),
        migrations.AddIndex(
            model_name="dispatchroute",
            index=models.Index(
                fields=["created_at"], name="dispatch_di_created_d28d9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["driver"], name="dispatch_di_driver__ca2b7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(fields=["status"], name="dispatch_di_status_873d01_idx"),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["assigned_at"], name="dispatch_di_assigne_3deea2_idx"
            ),
        ),
    ]
