# Generated by Django 5.1.6 on 2025-08-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_deleted_at_user_deletion_reason_user_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorlocation",
            name="postal_code",
        ),
    ]
