# Generated by Django 5.1.6 on 2025-08-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_remove_vendorlocation_postal_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorlocation",
            name="phone_number",
        ),
    ]
