# Generated by Django 5.1.6 on 2025-08-14 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_otpverification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="is_active",
        ),
        migrations.AddField(
            model_name="vendor",
            name="accepts_card",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="accepts_cash",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="accepts_mobile_money",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="average_preparation_time",
            field=models.PositiveIntegerField(
                default=30, help_text="Average preparation time in minutes"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="business_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="business_type",
            field=models.CharField(
                choices=[("restaurant", "Restaurant"), ("grocery", "Grocery Store")],
                default="restaurant",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="vendor_covers/"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="vendor",
            name="delivery_radius",
            field=models.PositiveIntegerField(
                default=5, help_text="Delivery radius in kilometers"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="vendor_logos/"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="minimum_order_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("inactive", "Inactive"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="tax_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendor",
            name="total_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="business_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="VendorLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Branch name or identifier", max_length=200
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="Tanzania", max_length=100)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "delivery_radius",
                    models.PositiveIntegerField(
                        default=5, help_text="Delivery radius in kilometers"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="authentication.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours",
                        to="authentication.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Business Hours",
                "unique_together": {("vendor", "day_of_week")},
            },
        ),
        migrations.CreateModel(
            name="VendorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="authentication.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vendor Categories",
                "unique_together": {("vendor", "name")},
            },
        ),
    ]
