# Generated by Django 5.1.6 on 2025-08-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_driver_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
