# Generated by Django 5.1.6 on 2025-08-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpverification",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="otpverification",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
