# Generated by Django 5.1.6 on 2025-08-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_order_quantity",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum quantity a customer can order for this product",
            ),
        ),
    ]
