# Generated by Django 5.1.6 on 2025-08-19 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("orders", "0002_product_max_order_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_categories",
                to="authentication.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("vendor", "name")},
        ),
    ]
