# Generated by Django 5.1.6 on 2025-08-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_category_vendor_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address_text",
            field=models.TextField(
                default="Unknown Address",
                help_text="Delivery address as text for non-registered users",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="special_instructions",
            field=models.TextField(
                blank=True, help_text="Customer's special instructions for the order"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.deliveryaddress",
            ),
        ),
    ]
