# Generated by Django 5.1.6 on 2025-08-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Importance/priority for ordering categories"
            ),
        ),
    ]
