# Generated by Django 5.1.6 on 2025-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_delivery_address_text_order_delivery_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
