# Generated by Django 5.1.6 on 2025-08-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_category_sort_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="order_item",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="product",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="category",
            name="sort_order",
        ),
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[("food", "Food"), ("grocery", "Grocery")],
                default="food",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a high-quality image of your product",
                null=True,
                upload_to="products/",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=0, help_text="Available stock quantity"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                default="piece",
                help_text="Unit of measurement (kg, piece, liter, etc.)",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="ProductReview",
        ),
        migrations.RemoveField(
            model_name="product",
            name="allow_backorder",
        ),
        migrations.RemoveField(
            model_name="product",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="product",
            name="compare_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="cost_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="inventory_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_gluten_free",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_vegan",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_vegetarian",
        ),
        migrations.RemoveField(
            model_name="product",
            name="low_stock_threshold",
        ),
        migrations.RemoveField(
            model_name="product",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="product",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="product",
            name="spice_level",
        ),
        migrations.RemoveField(
            model_name="product",
            name="status",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="product",
            name="track_inventory",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit_size",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
    ]
