# Generated by Django 5.1.6 on 2025-08-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_cart_session_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryaddress",
            name="postal_code",
        ),
    ]
