# Generated by Django 5.1.6 on 2025-08-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_deliveryaddress_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_country",
            field=models.CharField(blank=True, default="Tanzania", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_formatted_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_place_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_street_line2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_street_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address_text",
            field=models.TextField(
                blank=True,
                help_text="Delivery address as text for non-registered users",
            ),
        ),
    ]
