# Generated by Django 5.1.6 on 2025-08-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order_created", "Order Created"),
                    ("order_confirmed", "Order Confirmed"),
                    ("order_preparing", "Order Being Prepared"),
                    ("order_ready", "Order Ready for Pickup"),
                    ("order_available", "Order Available for Drivers"),
                    ("order_assigned", "Order Assigned"),
                    ("driver_en_route", "Driver En Route"),
                    ("driver_arrived", "Driver Arrived"),
                    ("order_picked_up", "Order Picked Up"),
                    ("order_in_transit", "Order In Transit"),
                    ("order_delivered", "Order Delivered"),
                    ("order_cancelled", "Order Cancelled"),
                    ("payment_received", "Payment Received"),
                    ("rating_received", "Rating Received"),
                    ("system_alert", "System Alert"),
                    ("location_update", "Location Update"),
                    ("status_update", "Status Update"),
                ],
                max_length=20,
            ),
        ),
    ]
